# HotpotQA — Raw Data Exploration

## 1. Load dataset

In [41]:
import os
from pathlib import Path

import pandas as pd
from datasets import load_dataset

In [42]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [23]:


ROOT      = Path(".").resolve()
HF_CACHE  = ROOT / "data" / "hotpotqa" / "hf_cache"

os.environ["HF_DATASETS_CACHE"] = str(HF_CACHE)

ds = load_dataset("hotpot_qa", "distractor", cache_dir=str(HF_CACHE))
print(ds)

DatasetDict({
    train: Dataset({
        features: ['id', 'question', 'answer', 'type', 'level', 'supporting_facts', 'context'],
        num_rows: 90447
    })
    validation: Dataset({
        features: ['id', 'question', 'answer', 'type', 'level', 'supporting_facts', 'context'],
        num_rows: 7405
    })
})

In [24]:
train_df = ds["train"].to_pandas()
val_df   = ds["validation"].to_pandas()

print(f"Train rows : {len(train_df):,}")
print(f"Validation rows: {len(val_df):,}")
train_df.head(3)

Train rows : 90,447
Validation rows: 7,405

                         id  \
0  5a7a06935542990198eaf050
1  5a879ab05542996e4f30887e
2  5a8d7341554299441c6b9fe5

                                                                                                                          question  \
0                                                           Which magazine was started first Arthur's Magazine or First for Women?
1                                                The Oberoi family is part of a hotel company that has a head office in what city?
2  Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?

                    answer        type   level  \
0        Arthur's Magazine  comparison  medium
1                    Delhi      bridge  medium
2  President Richard Nixon      bridge    hard

                                                                                              supporting_facts  \
0                                       {'title': ['Arthur's Magazine', 'First for Women'], 'sent_id': [0, 0]}
1                                          {'title': ['Oberoi family', 'The Oberoi Group'], 'sent_id': [0, 0]}
2  {'title': ['Allie Goertz', 'Allie Goertz', 'Allie Goertz', 'Milhouse Van Houten'], 'sent_id': [0, 1, 2, 0]}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              context
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {'title': ['Radio City (Indian radio station)', 'History of Albanian football', 'Echosmith', 'Women's colleges in the Southern United States', 'First Arthur County Courthouse and Jail', 'Arthur's Magazine', '2014–15 Ukrainian Hockey Championship', 'First for Women', 'Freeway Complex Fire', 'William Rast'], 'sentences': [['Radio City is India's first private FM radio station and was started on 3 July 2001.', ' It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003).', ' It plays Hindi, English and regional songs.', ' It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007.', ' Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features.', ' The Radio station currently plays a mix of Hindi and Regional music.', ' Abraham Thomas is the CEO of the company.'], ['Football in Albania existed before the Albanian Football Federation (FSHF) was created.', ' This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) .', ' Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946.', ' In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.'], ['Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California.', ' Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016.', ' Echosmith started first as "Ready Set Go!"', ' until they signed to Warner Bros.', ' Records in May 2012.', ' They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia.', ' The song was Warner Bros.', ' Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold.', ' The band's debut album, "Talking Dreams", was released on October 8, 2013.'], ['Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States.', ' Many started first as girls' seminaries or academies.', ' Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women.', ' Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.'], ['The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.'], ['Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century.', ' Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others.', ' In May 1846 it was merged into "Godey's Lady's Book".'], ['The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship.', ' Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues.', ' Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014.', ' The regular season included just 12 rounds, where all the teams went to the semifinals.', ' In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.'], ['First for Women is a woman's magazine published by Bauer Media Group in the USA.', ' The magazine was started in 1989.', ' It is based in Englewood Cliffs, New Jersey.', ' In 2011 the circulation of the magazine was 1,310,696 copies.'], ['The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California.', ' The fire started as two separate fires on November 15, 2008.', ' The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later.', ' These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.'], ['William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala.', ' It is most known for their premium jeans.', ' On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line.', ' The label also produces other clothing items such as jackets and tops.', ' The company started first as a denim line, later evolving into a men’s and women’s clothing line.']]}

## 2. Schema

In [25]:
train_df.dtypes

id                     str
question               str
answer                 str
type                   str
level                  str
supporting_facts    object
context             object
dtype: object

In [26]:
# One full example — shows nested structure
ex = train_df.iloc[0]
print("id             :", ex["id"])
print("question       :", ex["question"])
print("answer         :", ex["answer"])
print("type           :", ex["type"])
print("level          :", ex["level"])
print("supporting_facts:", ex["supporting_facts"])
print()
print("context titles :", ex["context"]["title"])
print("context[0]     :", ex["context"]["sentences"][0])

id             : 5a7a06935542990198eaf050
question       : Which magazine was started first Arthur's Magazine or First for Women?
answer         : Arthur's Magazine
type           : comparison
level          : medium
supporting_facts: {'title': array(["Arthur's Magazine", 'First for Women'], dtype=object), 'sent_id': array([0, 0], dtype=int32)}

context titles : ['Radio City (Indian radio station)' 'History of Albanian football'
 'Echosmith' "Women's colleges in the Southern United States"
 'First Arthur County Courthouse and Jail' "Arthur's Magazine"
 '2014–15 Ukrainian Hockey Championship' 'First for Women'
 'Freeway Complex Fire' 'William Rast']
context[0]     : ["Radio City is India's first private FM radio station and was started on 3 July 2001."
 ' It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003).'
 ' It plays Hindi, English and regional songs.'
 ' It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007.'
 ' Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features.'
 ' The Radio station currently plays a mix of Hindi and Regional music.'
 ' Abraham Thomas is the CEO of the company.']

## 3. Basic statistics

In [27]:
print("=== Question type distribution ===")
print(train_df["type"].value_counts())
print()
print("=== Difficulty level distribution ===")
print(train_df["level"].value_counts())

=== Question type distribution ===
type
bridge        72991
comparison    17456
Name: count, dtype: int64

=== Difficulty level distribution ===
level
medium    56814
easy      17972
hard      15661
Name: count, dtype: int64

In [28]:
train_df["q_len"] = train_df["question"].str.len()
train_df["a_len"] = train_df["answer"].str.len()

print("=== Question length (chars) ===")
print(train_df["q_len"].describe().round(1))
print()
print("=== Answer length (chars) ===")
print(train_df["a_len"].describe().round(1))

=== Question length (chars) ===
count    90447.0
mean       105.6
std         59.1
min         13.0
25%         69.0
50%         90.0
75%        120.0
max        654.0
Name: q_len, dtype: float64

=== Answer length (chars) ===
count    90447.0
mean        13.7
std         11.8
min          1.0
25%          7.0
50%         12.0
75%         17.0
max        623.0
Name: a_len, dtype: float64

In [29]:
# Number of supporting facts per question
train_df["n_supporting"] = train_df["supporting_facts"].apply(lambda x: len(x["title"]))
print("=== Supporting facts count ===")
print(train_df["n_supporting"].value_counts().sort_index())

=== Supporting facts count ===
n_supporting
2     63676
3     20017
4      5814
5       724
6       141
7        52
8        17
9         4
11        1
12        1
Name: count, dtype: int64

In [30]:
# Number of context articles per question (always 10 in distractor setting)
train_df["n_context"] = train_df["context"].apply(lambda x: len(x["title"]))
print("=== Context articles per question ===")
print(train_df["n_context"].value_counts())

=== Context articles per question ===
n_context
10    89609
2       262
3       156
4        94
5        88
7        77
8        60
6        53
9        48
Name: count, dtype: int64

## 4. Flatten context into passage-level rows

In [31]:
records = []
for _, row in train_df.iterrows():
    for title, sents in zip(row["context"]["title"], row["context"]["sentences"]):
        records.append({
            "qid":   row["id"],
            "title": title,
            "text":  " ".join(sents),
        })

passages_df = pd.DataFrame(records)
print(f"Total passages: {len(passages_df):,}")
passages_df.head(5)

Total passages: 899,667

,qid,title,text
0,5a7a06935542990198eaf050,Radio City (Indian radio station),"Radio City is India's first private FM radio station and was started on 3 July 2001. It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003). It plays Hindi, English and regional songs. It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007. Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features. The Radio station currently plays a mix of Hindi and Regional music. Abraham Thomas is the CEO of the company."
1,5a7a06935542990198eaf050,History of Albanian football,"Football in Albania existed before the Albanian Football Federation (FSHF) was created. This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) . Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946. In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA."
2,5a7a06935542990198eaf050,Echosmith,"Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California. Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016. Echosmith started first as ""Ready Set Go!"" until they signed to Warner Bros. Records in May 2012. They are best known for their hit song ""Cool Kids"", which reached number 13 on the ""Billboard"" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia. The song was Warner Bros. Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold. The band's debut album, ""Talking Dreams"", was released on October 8, 2013."
3,5a7a06935542990198eaf050,Women's colleges in the Southern United States,"Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States. Many started first as girls' seminaries or academies. Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women. Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level."
4,5a7a06935542990198eaf050,First Arthur County Courthouse and Jail,"The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum."

In [32]:
passages_df["text_len"] = passages_df["text"].str.len()
print("=== Passage text length (chars) ===")
print(passages_df["text_len"].describe().round(1))

=== Passage text length (chars) ===
count    899667.0
mean        546.1
std         336.0
min          24.0
25%         324.0
50%         483.0
75%         689.0
max        8268.0
Name: text_len, dtype: float64

## 5. Sample questions by type

In [33]:
print("=== Comparison questions (sample) ===")
sample = train_df[train_df["type"] == "comparison"][["question", "answer"]].sample(5, random_state=42)
for _, r in sample.iterrows():
    print(f"  Q: {r['question']}")
    print(f"  A: {r['answer']}")
    print()

=== Comparison questions (sample) ===
  Q: Were Theodore H. White and Hilaire Belloc both historians ?
  A: yes

  Q: Are Ralph Bakshi and Herschell Gordon Lewis both American?
  A: yes

  Q: What is from farther west, Killdozer or Skinny Puppy?
  A: Skinny Puppy

  Q: Which industry do Richard Hawley and Chicago's Catherine belong to?
  A: rock band

  Q: Ares and Right On!, is which type of publication?
  A: magazine

In [34]:
print("=== Bridge questions (sample) ===")
sample = train_df[train_df["type"] == "bridge"][["question", "answer"]].sample(5, random_state=42)
for _, r in sample.iterrows():
    print(f"  Q: {r['question']}")
    print(f"  A: {r['answer']}")
    print()

=== Bridge questions (sample) ===
  Q: Droga5 has completed advertisement campaigns for what founder and Chief Creative Officer of Ecko Unlimited?
  A: Marc Louis "Eckō" Milecofsky

  Q: When was the American baseball infielder, manager, and coach died who was hired by Emil Fuchs to replace him?
  A: January 5, 1963

  Q: Who distributed the film which featured a boy who had previously had no film experience?
  A: Warner Bros. Pictures

  Q: What is the place popular for which is in between Fair Harbor in Suffolk County and a village on Fire Island in the southern part of the Town of Islip in Suffolk County?
  A: kayaking

  Q: Who designed the theater that commissioned Benjamin Britten's opera?
  A: Joseph Bové

## 6. Validation set

In [35]:
print("=== Validation type distribution ===")
print(val_df["type"].value_counts())
print()
print("=== Validation level distribution ===")
print(val_df["level"].value_counts())
val_df[["question", "answer", "type", "level"]].head(5)

=== Validation type distribution ===
type
bridge        5918
comparison    1487
Name: count, dtype: int64

=== Validation level distribution ===
level
hard    7405
Name: count, dtype: int64

,question,answer,type,level
0,Were Scott Derrickson and Ed Wood of the same nationality?,yes,comparison,hard
1,What government position was held by the woman who portrayed Corliss Archer in the film Kiss and Tell?,Chief of Protocol,bridge,hard
2,"What science fantasy young adult series, told in first person, has a set of companion books narrating the stories of enslaved worlds and alien species?",Animorphs,bridge,hard
3,Are the Laleli Mosque and Esma Sultan Mansion located in the same neighborhood?,no,comparison,hard
4,"The director of the romantic comedy ""Big Stone Gap"" is based in what New York city?","Greenwich Village, New York City",bridge,hard

In [38]:
val_df[['question', 'answer']].head(20)

,question,answer
0,Were Scott Derrickson and Ed Wood of the same nationality?,yes
1,What government position was held by the woman who portrayed Corliss Archer in the film Kiss and Tell?,Chief of Protocol
2,"What science fantasy young adult series, told in first person, has a set of companion books narrating the stories of enslaved worlds and alien species?",Animorphs
3,Are the Laleli Mosque and Esma Sultan Mansion located in the same neighborhood?,no
4,"The director of the romantic comedy ""Big Stone Gap"" is based in what New York city?","Greenwich Village, New York City"
5,2014 S/S is the debut album of a South Korean boy group that was formed by who?,YG Entertainment
6,Who was known by his stage name Aladin and helped organizations improve their performance as a consultant?,Eenasul Fateh
7,The arena where the Lewiston Maineiacs played their home games can seat how many people?,"3,677 seated"
8,"Who is older, Annie Morton or Terry Richardson?",Terry Richardson
9,Are Local H and For Against both from the United States?,yes
10,"What is the name of the fight song of the university whose main campus is in Lawrence, Kansas and whose branch campuses are in the Kansas City metropolitan area?",Kansas Song
11,"What screenwriter with credits for ""Evolution"" co-wrote a film starring Nicolas Cage and Téa Leoni?",David Weissman
12,What year did Guns N Roses perform a promo for a movie starring Arnold Schwarzenegger as a former New York Police detective?,1999
13,Are Random House Tower and 888 7th Avenue both used for real estate?,no
14,The football manager who recruited David Beckham managed Manchester United during what timeframe?,from 1986 to 2013
15,Brown State Fishing Lake is in a country that has a population of how many inhabitants ?,"9,984"
16,The Vermont Catamounts men's soccer team currently competes in a conference that was formerly known as what from 1988 to 1996?,the North Atlantic Conference
17,Are Giuseppe Verdi and Ambroise Thomas both Opera composers ?,yes
18,Roger O. Egeberg was Assistant Secretary for Health and Scientific Affairs during the administration of a president that served during what years?,1969 until 1974
19,"Which writer was from England, Henry Roth or Robert Erskine Childers?",Robert Erskine Childers DSC

### EVALUATION ANALYSIS

In [43]:
eval_df = pd.read_csv('./results/eval_20260515_160704.csv')

In [44]:
eval_df

,id,question,real_answer,llm_answer
0,5ae143ed55429920d5234360,In what year was the university where Sergei Aleksandrovich Tokarev was a professor founded?,1755,I cannot find the answer in the provided context.
1,5abc19705542993a06baf86e,Black Book starred the actress and writer of what heritage?,Dutch,Dutch
2,5ac3e0f7554299194317388b,Which actor does American Beauty and American Beauty have in common?,Kevin Spacey,Kevin Spacey
3,5ae518655542993aec5ec139,Ken Pruitt was a Republican member of an upper house of the legislature with how many members ?,40 members,40
4,5ab985eb554299131ca42360,"Between Greyia and Calibanus, which genus contains more species?",Greyia,yes
5,5a8753d95542994846c1cd63,Did John Updike and Tom Clancy both publish more than 15 bestselling novels?,yes,yes
6,5ab97d0a5542996be202051e,Who was hung for assisting the attempted surrender of a defector from the American Continental Army to the British Army?,John André,John André
7,5adef1b35542993a75d263af,which Mexican and American film actress is Ethel Houbiers French voice of,Salma Hayek Pinault,Salma Hayek
8,5a73b55855429978a71e9086,Which major international airport in south-east England ranks as the 8th busiest airport in Europe and replaced Croydon Airport?,Gatwick Airport,Gatwick
9,5ae80919554299540e5a56f6,Isabella Kelly was born at a ruined castle characterized as one of the most isolated fortifications in Britain by who?,The Changing Scottish Landscape,I cannot find the answer in the provided context.
10,5ae361605542994393b9e69b,The facility where Robert Croft worked as a navy instructor was also known as?,"""Home of the Submarine Force""",US Naval Submarine Base
11,5ac3a76e554299741d48a2be,"Who released the song ""With or Without You"" first, Jai McDowall or U2?",U2,U2
12,5a7557d75542992d0ec05f68,"Which ""Roseanne"" star is in Scream 2?",Laurie Metcalf,Jerry O'Connell
13,5a8d12ca5542994ba4e3dbe2,In what city is the company that Fastjet Tanzania was originally founded as a part of prior to rebranding based?,"Nairobi, Kenya",I cannot find the answer in the provided context.
14,5ab7f6d35542993667794070,"What is the name of the Australian specialist electronic music magazine that features avant-rock, experimental sound art, and experimental hip hop?",Cyclic Defrost,Cyclic Defrost
15,5ac3d9135542995c82c4ac4c,What is the population of the city that Munsonville is in the northwest corner of?,729 at the 2010 census,I cannot find the answer in the provided context.
16,5ae129115542990adbacf722,A Pair of Brown Eyes and Wild Mountain Thyme is based from what artists song?,Francis McPeake,The McPeakes
17,5a86769c5542994775f60776,Armageddon in Retrospect was written by the author who was best known for what 1969 satire novel?,Slaughterhouse-Five,Slaughterhouse-Five
18,5ab31864554299233954ff06,What class of instrument does Apatim Majumdar play?,strings,Sarod
19,5a7b1023554299042af8f6c2,"Which movie did Disney produce first, The Many Adventures of Winnie the Pooh or Ride a Wild Pony?",Ride a Wild Pony,The Many Adventures of Winnie the Pooh
20,5ac19f405542991316484b5b,Pandikona and Berger Blanc Suisse are both what kinds of animals?,dogs,not mentioned
21,5ae382ee5542992e3233c430,The Prussian General Carl von Clausewitz is associated with what type of realism?,Modern thinkers associated with classical realism are Carl von Clausewitz,classical
22,5adcdf455542994ed6169c11,What where both Hawker Hurricane and No. 1455 Flight apart of?,Royal Air Force,RAF
23,5ac35a7e554299741d48a257,what language did the ethnic group which Torstein Ellingsen was its drumer speaks,Norwegian language,I cannot find the answer in the provided context.
24,5ab2659e554299340b5254b2,"From March 631 to April 631, Farrukhzad Khosrau V was the king of an empire that succeeded which empire?",the Parthian Empire,Sasanian Empire
25,5adcbb815542994ed6169bde,"Beer Wars covers the differences between large corporate breweries, and small breweries, such as what brewery that is headquartered in Escondido, california?",Stone Brewing,I cannot find the answer in the provided context.
26,5a74f8bd5542993748c8976a,"Which head coach has led their team for a longer period of time, Tim Cluess or Steve Prohm?",Tim Cluess,yes
27,5ade25ed5542997c77aded70,During what war were the Russia-United Kingdom relations in a state of rivalry after the abdication of Emperor Nicholas II?,the Cold War (1947–91),Cold War
28,5a78ae8b5542990784727730,How far from Sacramento is the flight school in Atwater?,about 115 miles (185 km),115 miles
29,5ae12a4b55429920d52342df,Baraki Barak District is situated in the western part of a province whose capital is what?,Puli Alam,I cannot find the answer in the provided context.
30,5ae22eae554299495565da30,What was the 2010 population of the town where Black Crescent Mountain was located?,310,I cannot find the answer in the provided context.
31,5ab6aa4c55429953192ad359,"In the NASA mission where Moon trees were taken into space, what was the nickname of the Command Module?","""Kitty Hawk""",I cannot find the answer in the provided context.
32,5adf3e835542993a75d26442,Which comic series involves characters such as Nick Fury and Baron von Strucker?,Marvel,Strange Tales
33,5a8ee3a755429917b4a5be02,College Humor is a 1933 American pre-Code musical comedy film that starred what American singer and actor who has a trademark warm bass-baritone voice?,"Harry Lillis ""Bing"" Crosby Jr.",Bing Crosby
34,5ac0dcf25542996f0d89cc2c,Who is writing a book about the Koch family who control the second-largest privately owned company in the United States?,Jane Mayer,Jane Mayer
35,5a7e618155429949594199b0,New York State Route 9R rejoins its parent in a hamlet located in what New York County?,Albany,Albany
36,5ab916e155429919ba4e23a4,12 Years a Slave starred what British actor born 10 July 1977),Chiwetel Ejiofor,Chiwetel Ejiofor
37,5a713b325542994082a3e6b5,What was the capital of India when the Taj Mahal was commissioned?,Agra,Agra
38,5a87c13f5542996e4f30890c,"In what city did the ""Prince of tenors"" star in a film based on an opera by Giacomo Puccini?",Rome,I cannot find the answer in the provided context.
39,5a8843cd5542994846c1ce75,What river can a large African bovine be seen bathing in in the Mwabvi Wildlife Reserve?,Buffalo,Mwabvi river
40,5ab90d8955429916710eb0f1,Jalen Jones plays basketball for an NBA team that plays their home games in what arena?,Smoothie King Center,Smoothie King Center
41,5ae788fa55429952e35ea964,The On Tour Forever album gave Blues Traveler the opportunity to display what musical trademark?,extensive use of segues,jam band sound
42,5ae1925a554299492dc91b48,Which Victorian poet was born in a 15th-century castle home to the Earl of Southesk?,Charlotte Carnegie,yes
43,5ae1443855429920d5234362,Alexander Petrovich Nikolayev received the title Hero of the Soviet Union and the Order of Lenin for his actions during the the final major offensive of the European theatre of what war?,World War II,World War II
44,5ac54c435542993e66e822d1,Where did Cale Gundy's brother play football in college?,Oklahoma State University,I cannot find the answer in the provided context.
45,5a7a77425542995eb53be83e,"Who has released more solo albums, Nick Carter or Brady Seals?",Brady Seals,They are equal.
46,5a7153d05542994082a3e7dc,"Which Istanbul mosque is unique for retaining a Baroque style of architecture, the Bayezid II Mosque or the Nusretiye Mosque?",Nusretiye Mosque,Nusretiye
47,5ae361805542992e3233c3c9,"What university did the last Detroit Pistons player to wear the number retired in honor of a player nicknamed ""The Worm"" attend?",Georgetown University,Georgetown
48,5a72688c5542997f827839b2,The Atik Valide Mosque and Valens Aqueduct are found in what country?,Turkey,Turkey
49,5a7ce0ce554299452d57ba92,"Which of the four US Presidents who have been assinated was shot on the grounds of the Pan-American Exposition at the Temple of Music in Buffalo, New York?",William McKinley,McKinley
50,5a83411655429966c78a6b5d,Who created the NBC sitcom that Johnny Pemberton appears in as the character Bo Thompson?,Justin Spitzer,I cannot find the answer in the provided context.
51,5a877dd65542993e715abf79,Were Halldór Laxness and Timothy Leary from the same country?,no,no
52,5ab6087a554299110f2199be,Do both Korematsu v. United States and Chaplinsky v. New Hampshire cases regard the rights of U. S. citizens?,yes,no
53,5adbd70c55429947ff173843,What is the title of the memoir written by the honoree of the Black and White Ball?,Personal History,Our Nig
54,5a7796e05542992a6e59df0f,What country is the theme park served by the Huis Ten Bosch train service themed on?,Netherlands,Netherlands
55,5abc030e554299642a094bdc,The Distribution of Industry act was passed by a man who was prime minister when?,1945 to 1951,After WWII
56,5a7bb7f2554299042af8f7b6,"What Cantonese slang term can mean both ""ghost man"" and to refer to Westerners?",Gweilo,yes
57,5a8b3de95542997f31a41cc3,In what year was the most famous statute at Po Lin Monastery built?,Tian Tan Buddha,1993
58,5ab3bfd3554299233954ff99,"The Nike Hoop Summit has had many current NBA players as former participants, including what German player from the Dallas Mavericks?",Dirk Werner Nowitzki,yes
59,5ab9b7d555429970cfb8eb7a,Which actor from the South Korean-Thai drama film Final Recipe debuted as a member of Super Junior-M in 2008?,Henry Lau,2015
60,5ab6bf6d55429953192ad372,Are Phlebodium and Pieris both species of ferns?,no,no
61,5ae7cb9b5542994a481bbde2,Who was the great grandfather of Franklin Seaver Pratt's wife?,Kalokuokamaile,I cannot find the answer in the provided context.
62,5ab1d6545542997061209588,At what age did Cieli di Toscana's singer become blind?,Bocelli became completely blind at the age of 12,I don't have the answer
63,5addcb215542997dc7907033,Which late 1980s and 1990s English super model was featured in the song nasty girl by The Notorious B.I.G.?,Naomi Elaine Campbell,I couldn't find it.
64,5ae528ed5542993aec5ec16e,What is the name of the film directed by Alex Cox adapted from a 1606 play starring Diana Quick as the Dutchess?,Revengers Tragedy,Revengers Tragedy
65,5a8c7ced5542995e66a4761c,Josh Trank and Mike Valerio both work in what industry?,entertainment,yes
66,5a72f74a55429901807daf59,"Which American comedian born on March 21, 1962, appeared in the movie ""Sleepless in Seattle?""",Rosie O'Donnell,no
67,5ae1d4e8554299234fd04312,Any Questions for Ben? was directed by which Australian producer and actor?,"Robert Ian ""Rob"" Sitch",Rob Sitch
68,5a80aeef5542992097ad301a,What American indie rock group first had Jesse Sandoval as the drummer and now has Jon Sortland on drums?,The Shins,The Shins
69,5a7f66f155429969796c1a33,What 3 countries are part of the legal name of the airline that merged with Braathens in 2004?,Denmark–Norway–Sweden,Norway
70,5abbda84554299642a094b5b,What is the ratio of flow velocity past a boundary to the local speed of sound for a Saab JAS 39 Gripen?,2,I cannot find the answer in the provided context.
71,5abe3dc65542993f32c2a0c4,"SWX Right Now airs on the station that broadcasts on what channel in Billings, Montana?",8,I cannot find the answer in the provided context.
72,5ae489ab5542995ad6573d62,"Which player, who also played for the New Jersey Nets and the Golden State Warriors, finished third in the league with 231 three-point field goals during the 1995-96 Atlanta Hawks season?",Mookie Blaylock,Mookie Blaylock
73,5a7e1b7155429965cec5ea6c,Saltillo Engine is an engine plant in Ramos Arizpe that belongs to the American subsidiary of what company?,Fiat Chrysler Automobiles N.V.,Chrysler
74,5a8fae205542997ba9cb32ec,"What type of television show did Dylan Everett star in, in 2015?",American-Canadian mystery-drama,Open Heart
75,5ae588cb55429960a22e0300,"Which plant, the Chaerophyllum or the Cryptanthus, can be found in various places across the world?",Chaerophyllum,Chaerophyllum
76,5a75e62f5542992d0ec06013,"Johnny Mathis: Wonderful Wonderful aired at what luxury hotel, casino and spa resort located in Atlantic City, New Jersey?",Tropicana Casino & Resort,Tropicana
77,5ac113e2554299294b21909a,Who wrote the lyrics for Linda Eder's Broadway debut?,"Wildhorn, Bricusse and Cuden",I cannot find the answer in the provided context.
78,5a82fe5055429966c78a6ad3,"The Company They Keep is a book written by Diana Pavlac Glyer, who is a professor at a university in Azusa, California, that was founded in 1899, and is under the auspices of what religion?",evangelical Christian,Wesleyan-Arminian
79,5a7e05ba5542995f4f402392,For One Night Only was hosted by the man most well-known for hosting what show from 1962 until 1999?,The Late Late Show,The Late Late Show
80,5a7264ed5542990c210a411a,What was the slogan that came about from the idea of Lebensraum which had its most extreme form supported by the Nazi Party until the end of World War II?,Blood and soil,Blood and Soil
81,5a8ed10b5542995085b374a0,Olivia DeJonge starred in an American horror film directed by Shyamalan called what,The Visit,The Visit
82,5add8f055542990dbb2f7e6d,Who conducted the negotiations with the owners and the longest serving commandant of Auschwitz concentration and extermination camp?,Rudolf Höss,I cannot find the answer in the provided context.
83,5a86ab7755429960ec39b6bf,What genre is the novel from which the fast-food restaurant specializing in seafood derives its name?,an adventure novel,pirate fiction
84,5a7a112a5542990783324e2b,What kind of musicians are Mark Gaudet and Jan Axel Blomberg?,drummer,metal
85,5ab870ee5542990e739ec8f6,A Wind in the Door is part of a series written by who?,Madeleine L'Engle,Madeleine L'Engle
86,5a8810485542997e5c09a590,The Airport located next to the A13 handled how many passengers in 2016 ?,1.6 million passengers,18.3 million
87,5a8208ee5542990a1d231f1e,"The town of Sinclair, West Virginia, is named after the founder of the local oil drilling company. What is on Sinclair Oil's famous logo?",dinosaur,A green dinosaur
88,5a86399e5542994775f60733,Jihad: A Story of the Others is a documentary by the director who is of what descent?,Punjabi/Pashtun,Norwegian
89,5a78e9a2554299148911f995,Minor league baseball games that were played between the rivalling teams of the Sooners and the Cowboys were played at the stadium formerly known as what?,Drillers Stadium,I cannot find the answer in the provided context.
90,5a84995d5542997b5ce3fee4,Cooperative Living Organization is located in a city that is the county seat of what county in Florida?,Alachua,I cannot find the answer in the provided context.
91,5ab941c2554299743d22ea88,"What is the pen name of author Carolyn Janice Cherry, who wrote the Fortress Series?","Carolyn Janice Cherry (born September 1, 1942), better known by the pen name C. J. Cherryh,",C. J.
92,5a8e5f1f5542995a26add4d6,"Which dog is believed to dispel ghosts and evil spirits, Segugio Italiano or Sapsali?",Sapsali,yes
93,5abf1ad15542997ec76fd3c2,"Which French aristocrat and military officer who fought in the American Revolutionary War visited this historic home located at Enfield, Halifax County, North Carolina, known as The Cellar?",Marquis de Lafayette,I cannot find the answer in the provided context.
94,5ae5cf625542996de7b71a22,What sports team included both of the brothers Case McCoy and Colt McCoy during different years?,University of Texas Longhorns,University of Texas
95,5a7c8ae855429935c91b5207,Which member of The New Russian School was both a doctor and a chemist besides being a composer?,Alexander Porfiryevich Borodin,Alexander Borodin
96,5a87106555429960ec39b71f,"Susanna Thompson appeared in the courtroom drama film Ghosts of Mississippi, directed by who?",Rob Reiner,Rob Reiner
97,5a7f296f55429934daa2fd10,Live Wire Radio will possibly be considered as a replacement for a variety show created in what year?,1974,I cannot find the answer in the provided context.
98,5ae14b5c55429920d52343aa,Luke Rockhold defeated the MMA fighter who was the first to earn a win against which champion in the UFC?,Anderson Silva,I cannot find the answer in the provided context.
99,5a88b3b4554299206df2b336,What type of art does The Consul and Arlecchino have in common?,music,I cannot find the answer in the provided context.

In [46]:
eval_metrics = pd.read_json('./results/smoke.json')

ValueError: Trailing data